INSERT IGNORE INTO products (location_id, name, price, days, seats, image_url, detail_url,status, created_at, updated_at)
VALUES (31, '도쿄 벚꽃 여행 3일', 890000, 3, 30, '/images/package/tokyo.jpg','/images/detail/tokyo.jpg', 'AVAILABLE', NOW(), NOW()),
       (30, '오사카 맛집 탐방 4일', 950000, 4, 25, '/images/package/osaka.jpg', '/images/detail/osaka.jpg','AVAILABLE', NOW(), NOW()),
       (29, '후쿠오카 쇼핑 여행 3일', 880000, 3, 20, '/images/package/fukuoka.jpg', '/images/detail/fukuoka.jpg','AVAILABLE', NOW(), NOW()),
       (30, '교토 문화 탐방 3일', 920000, 3, 20, '/images/package/kyoto1.jpg','/images/detail/osaka.jpg', 'AVAILABLE', NOW(), NOW()),
       (30, '교토 시내 온천 3일', 5990000, 3, 13, '/images/package/kyoto2.jpg', '/images/detail/osaka.jpg','AVAILABLE', NOW(), NOW()),
       (32, '오키나와 휴양 여행 4일', 1380000, 4, 25, '/images/package/okinawa1.jpg','/images/detail/okinawa1.jpg', 'AVAILABLE', NOW(), NOW()),
       (32, '오키나와 리조트 5일', 2980000, 5, 25, '/images/package/okinawa2.jpg', '/images/detail/okinawa2.jpg','AVAILABLE', NOW(), NOW()),
       (8, '방콕 힐링 여행 5일', 1150000, 5, 40, '/images/package/bangkok.jpg', '/images/detail/bangkok.jpg','AVAILABLE', NOW(), NOW()),
       (16, '다낭 가족 여행 4일', 1050000, 4, 35, '/images/package/danang.jpg', '/images/detail/danang.jpg','AVAILABLE', NOW(), NOW()),
       (58, '타이베이 미식 여행 3일', 870000, 3, 30, '/images/package/taipei.jpg', '/images/detail/taipei.jpg','AVAILABLE', NOW(), NOW()),
       (47, '북경(베이징) 만리장성 4일', 699000, 4, 15, '/images/package/beijing.jpg', '/images/detail/beijing.jpg','AVAILABLE', NOW(), NOW()),
       (48, '상하이 도심 투어 4일', 549000, 4, 15, '/images/package/sanghai1.jpg', '/images/detail/sanghai1.jpg','AVAILABLE', NOW(), NOW()),
       (48, '상하이 디즈니랜드 4일', 599000, 4, 15, '/images/package/sanghai2.jpg','/images/detail/sanghai2.jpg', 'AVAILABLE', NOW(), NOW()),
       (11, '싱가포르 야경 여행 5일', 1190000, 5, 30, '/images/package/singapore.jpg','/images/detail/singapore.jpg', 'AVAILABLE', NOW(), NOW()),
       (1, '파리 낭만 여행 7일', 2890000, 7, 15, '/images/package/paris.jpg','/images/detail/paris.jpg', 'AVAILABLE', NOW(), NOW()),
       (1, '런던 시티 투어 6일', 2750000, 6, 20, '/images/package/london.jpg','/images/detail/london.jpg', 'AVAILABLE', NOW(), NOW()),
       (1, '로마 예술 여행 5일', 2650000, 5, 18, '/images/package/roma.jpg', '/images/detail/roma.jpg','AVAILABLE', NOW(), NOW()),
       (67, '뉴욕 자유 여행 6일', 3150000, 6, 25, '/images/package/newyork.jpg', '/images/detail/newyork.jpg','AVAILABLE', NOW(), NOW()),
       (66, '로스앤젤레스 해변 여행 7일', 2980000, 7, 13, '/images/package/losangeles.jpg','/images/detail/losangeles.jpg', 'AVAILABLE', NOW(), NOW()),
       (6, '스위스 알프스 하이킹 6일', 3100000, 6, 20, '/images/package/swiss.jpg','/images/detail/swiss.jpg', 'AVAILABLE', NOW(), NOW()),
       (2, '프라하 감성 여행 5일', 2550000, 5, 20, '/images/package/praha.jpg','/images/detail/praha.jpg', 'AVAILABLE', NOW(), NOW());
